version: '3'
services:
  rust:
    image: "rust:latest"
    working_dir: /usr/src/myapp
    volumes:
      - /blockchain:/usr/src/myapp
    command: cargo run
    links:
      - mongo

  golang:
    image: "golang:1.10.2-stretch"
    working_dir: /go/src/app
    volumes:
      - /backend_go:/go/src/app
    command: go run index.go
    links:
      - db


  py_test:
    image: "python:3.7.0b3-alpine3.7"
    working_dir: /usr/src/app
    volumes:
      - /e2e_test:/usr/src/app
    command: python main.py
    links:
      - golang
      - rust
      - react


  react:
    image: "node:9.11.1-alpine"
    working_dir: /home/node/app
    volumes:
      - /frontend:/home/node/app
    command: /bin/sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    links:
      - golang

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    expose:
      - "5432"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass