version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
    expose:
      - "5432"
    ports:
      - "5432:5432"

  golang:
    image: "golang:1.10.2-stretch"
    working_dir: /go/src/app
    volumes:
     - ./backend_go:/go/src/app
    command: /bin/sh -c "go get github.com/gin-gonic/gin && go get github.com/gin-contrib/cors && go get github.com/jinzhu/gorm && go get github.com/jinzhu/gorm/dialects/postgres && go run index.go"
    links:
     - db
    ports:
     - "8080:8080"