// @flow

export const LOGIN_REQUEST: string = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE: string = 'LOGIN_FAILURE';

export const LOGOUT: string = 'LOGOUT';

export const REGISTER_REQUEST: string = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: string = "REGISTER_SUCCESS";
export const REGISTER_FAILURE: string = "REGISTER_FAILURE";

export const ALL_DEVICES_REQUEST: string = "ALL_DEVICES_REQUEST";
export const ALL_DEVICES_SUCCESS: string = "ALL_DEVICES_SUCCESS";
export const ALL_DEVICES_FAILURE: string = "ALL_DEVICES_FAILURE";

export const SWITCH_REQUEST: string = "SWITCH_REQUEST";
export const SWITCH_SUCCESS: string = "SWITCH_SUCCESS";
export const SWITCH_FAILURE: string = "SWITCH_FAILURE";

export const CHANGE_BRIGHTNESS_REQUEST: string = "CHANGE_BRIGHTNESS_REQUEST";
export const CHANGE_BRIGHTNESS_SUCCESS: string = "CHANGE_BRIGHTNESS_SUCCESS";
export const CHANGE_BRIGHTNESS_FAILURE: string = "CHANGE_BRIGHTNESS_FAILURE";

export const ADD_DEVICE_REQUEST: string = "ADD_DEVICE_REQUEST";
export const ADD_DEVICE_SUCCESS: string = "ADD_DEVICE_SUCCESS";
export const ADD_DEVICE_FAILURE: string = "ADD_DEVICE_FAILURE";

export const DELETE_DEVICE_REQUEST: string = "DELETE_DEVICE_REQUEST";
export const DELETE_DEVICE_SUCCESS: string = "DELETE_DEVICE_SUCCESS";
export const DELETE_DEVICE_FAILURE: string = "DELETE_DEVICE_FAILURE";

export const CREATE_WALLET_REQUEST: string = "CREATE_WALLET_REQUEST";
export const CREATE_WALLET_SUCCESS: string = "CREATE_WALLET_SUCCESS";
export const CREATE_WALLET_FAILURE: string = "CREATE_WALLET_FAILURE";

export const GET_WALLET_REQUEST: string = "GET_WALLET_REQUEST";
export const GET_WALLET_SUCCESS: string = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAILURE: string = "GET_WALLET_FAILURE";

export const SEND_MONEY_REQUEST: string = "SEND_MONEY_REQUEST";
export const SEND_MONEY_SUCCESS: string = "SEND_MONEY_SUCCESS";
export const SEND_MONEY_FAILURE: string = "SEND_MONEY_FAILURE";

export const GET_TRANSACTION_HISTORY_REQUEST: string = "GET_TRANSACTION_HISTORY_REQUEST";
export const GET_TRANSACTION_HISTORY_SUCCESS: string = "GET_TRANSACTION_HISTORY_SUCCESS";
export const GET_TRANSACTION_HISTORY_FAILURE: string = "GET_TRANSACTION_HISTORY_FAILURE";

